### ISSUE TITLE
What do width and height default to?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [direct-adv-interfaces/mocha-headless-chrome#10]
It's not clear from the README.md or source code?

**Comment by dima117** [comment]
Viewport width and height parameters belongs to puppeteer. `mocha-headless-chrome` just passes their width and height parameters into puppeteer. If this parameters is not specified, puppeteer default values is used.

As I know puppeteer default values is 800x600.

**Comment by dima117** [comment]
It's strange that you asked this question. If the viewport size is affected to your tests, you can specify it in the parameters. If the viewport size is not important, then you do not need to know the default values.
