### ISSUE TITLE
Provide TypeScript typings?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [direct-adv-interfaces/mocha-headless-chrome#11]
https://github.com/DefinitelyTyped/DefinitelyTyped/
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21760
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21762

It's useful for TypeScript typings to be published as a part of JavaScript packages. That way they don't get out of sync with the packages themselves.

**Comment by dima117** [comment]
Yes, it's a good idea. Could you make a PR?
