### ISSUE TITLE
Code coverage?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [direct-adv-interfaces/mocha-headless-chrome#13]
Could you provide a sample of how this be used with, say, istanbul/nyc please?

**Comment by dima117** [comment]
Hi,

I'm sorry for the very late reply.

I added the additional `-c` CLI parameter which specifies the path where coverage info should be saved. mocha-headless-chrome@1.8.1 package is published.

You need to perform five steps:

1. Install the [istanbul](https://www.npmjs.com/package/istanbul) coverage tool;
2. instrument your code which you want to test using the `instrument` command of the istanbul CLI;
3. include instrumented code into your test page instead the original code;
4. run the tests by mocha-headless-chrome using `-c` parameter like this:

```
$ mocha-headless-chrome -f example-page.html -c coverage.json
```
All the coverage info will be saved into the `coverage.json` file.

5. generate coverage report using the `report` command of the istanbul CLI.

I will soon add a small example project.

**Comment by JoshuaKGoldberg** [comment]
Finally got around to trying this out - works like a charm! Thanks so much!

I'll send a PR adding brief additional instructions for getting an HTML report out of it to README.md.
