### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Diokuz** [direct-adv-interfaces/mocha-headless-chrome#14]
Hi there!

I have a problem: when I run `mocha-headless-chrome`, I have no output:

```
$ node_modules/.bin/mocha-headless-chrome -f ./test.inbrowser/build/index.html -r tap
%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq font-weight:bold
$ 
```

If some tests are going to fail, I have just +1 line `tests failing`

```
$ node_modules/.bin/mocha-headless-chrome -f ./test.inbrowser/build/index.html -r tap
%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq font-weight:bold
Tests fails
$ 
```

I tried to change `-r` option to `spec`, `dot` – none of them works. How can I fix that?

```
npm list | grep mocha-headless-chrome
├─┬ mocha-headless-chrome@1.7.1
```

**Comment by Diokuz** [comment]
That was simple: I had `mocha.reporter('html')` in my `index.html` file. Looks like `mocha-headless-chrome` cannot override reporter if it already has been set up.

**Comment by dima117** [comment]
Hi

It's correct behavior: the reporter specified on the page has a higher priority than the reporter specified in the CLI parameter.

**Comment by dima117** [comment]
I think I can close this issue since it isn't active during several days. If you have any additional questions please open this issue again.
