### ISSUE TITLE
Running in Travis

### ISSUE THREAD

**Issue by robhicks** [direct-adv-interfaces/mocha-headless-chrome#15]
I've been using mocha-headless-chrome in travis for continuous integration for a while.

However, this week, the mocha-headless-chrome test runner has started failing in Travis. 

At first, I thought it was an issue with puppeteer sandboxing so I tried starting mocha-headless-chrome as follows:

mocha-headless-chrome -a no-sandbox,disable-setuid-sandbox -f http://127.0.0.1:${port}/demo/mocha.html

That didn't work. 

Has anyone else seen this issue?

Am I setting the puppeteer arguments correctly?

I'm getting errors like the following repeated:

```
ERROR: { Error: watch /home/travis/build/fs-webdev/idx-new-admin-app/node_modules/shebang-command/license ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1374:19)
    at Object.fs.watch (fs.js:1400:11)
    at createFsWatchInstance (/home/travis/build/fs-webdev/idx-new-admin-app/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/travis/build/fs-webdev/idx-new-admin-app/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/travis/build/fs-webdev/idx-new-admin-app/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/travis/build/fs-webdev/idx-new-admin-app/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/travis/build/fs-webdev/idx-new-admin-app/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:153:5)
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/travis/build/fs-webdev/idx-new-admin-app/node_modules/shebang-command/license',
  filename: '/home/travis/build/fs-webdev/idx-new-admin-app/node_modules/shebang-command/license' }
```

**Comment by dima117** [comment]
Hi,

try to use separated `-a` argument for each chrome parameter:

```
$ mocha-headless-chrome -f test.html -a no-sandbox -a disable-setuid-sandbox
```

**Comment by robhicks** [comment]
Thanks for the tip. Unfortunately, it didn't work.

**Comment by dima117** [comment]
Also the puppeteer was updated today and I released a new 1.8.1 version of the mocha-headless-chrome package. Try to use it.

**Comment by robhicks** [comment]
In your start script you have:
node cli -f example-page.html -o result.json -c coverage.json -w 801 -H 501 -a no-sandbox -a disable-setuid-sandbox

What is cli?

**Comment by dima117** [comment]
Could you provide the exact script which you use to execute the tests?

**Comment by robhicks** [comment]
I have not been running it as you do with the -f flag. When I run it from the command line with -f flag all of the tests fail.  Instead, I've been spinning up a server. Here's my start script:
```JavaScript
const liveServer = require('live-server');
const exec = require('child_process').exec;
const port = 25000;

const params = {
  port: port,
  host: "0.0.0.0",
  root: 'demo',
  file: 'mocha.html',
  mount: [['/components', './components'], ['/dist', './dist'], ['/assets', './assets'], ['/node_modules', './node_modules']],
  open: false,
  wait: 500,
  logLevel: 2
};

liveServer.start(params);

setTimeout(() => {
  exec(`./node_modules/.bin/mocha-headless-chrome -f http://127.0.0.1:${port}/demo/mocha.html -a no-sandbox -a disable-setuid-sandbox`, (err, stdOut, stdErr) => {
    console.log("stdOut", stdOut);
    liveServer.shutdown();
    if (err) process.exit(-1);
    else process.exit(0);
  });
}, 500);
```

**Comment by robhicks** [comment]
Based upon your comment about chokidar, I swapped live-server out in my script with a generic node http server and the tests now work on again on Travis.

Thanks for your help!
