### ISSUE TITLE
--watch

### ISSUE THREAD

**Issue by robhicks** [direct-adv-interfaces/mocha-headless-chrome#2]
Thanks for the package. It works great. 

Are there any plans to add a watcher for development mode?

**Comment by dima117** [comment]
Hi, 

yes, it is a good idea. I will try to add this functionality. Do you have any understanding how it should work?

**Comment by robhicks** [comment]
Mocha supports --watch. Can tie directly into it's functionality?

**Comment by dima117** [comment]
When mocha works in the browser, the entry point is the page where mocha, tests and testable code are included. With this in mind, describe what files the watcher should observe and what tests should be performed when the files are changed.

**Comment by robhicks** [comment]
You could watch all the files included in the head tag and the scripts included in the body tag. Of course, you could exclude mocha.css and mocha.js in the head tag. 

When a file change is detected, seems it would make sense to reload the html file.

**Comment by dima117** [comment]
I'm sorry for the very late reply.

I thought about variants of the watcher API and did not find a good solution. Also it looks like the mocha-headless-chrome takes on excessive responsibility.

As a workaround I propose to use an external watcher, for example [chokidar-cli](https://github.com/kimmobrunfeldt/chokidar-cli). You can run a watcher as follows:

```
chokidar '**/*.js' '**/*.test.js' -c 'npm test'
```

Please let me know if this has solved your problem.

**Comment by robhicks** [comment]
No worries. I'll give it a try. Thanks!
