### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by ncoden** [direct-adv-interfaces/mocha-headless-chrome#24]
Hi,

What is the changlog for v2.0.0.
* What did changed ?
* Why does this require a major version bump ?
* Is there any breaking changes ?

It would be useful to add a `CHANGELOG.md` file, and to add the same description to each GitHub release. See https://keepachangelog.com if you need any help.

**Comment by dima117** [comment]
Hi,

Breaking changes is [there](https://github.com/direct-adv-interfaces/mocha-headless-chrome/commit/ad8073d7b264b48b10f58f4ae2b55a2159f169fd#diff-b3b53682a18f203ac8d29b0e277cad26R144) (it can break the projects that use the mocha-headless-chrome programmatically).

I will add CHANGELOG.md soon.

**Comment by ncoden** [comment]
Thank you! 👍

**Comment by dima117** [comment]
Done.

I'm sorry for the large delay.
