### ISSUE TITLE
Coverage support

### ISSUE THREAD

**Issue by gits2501** [direct-adv-interfaces/mocha-headless-chrome#25]
Hello. Does m-h-c requires that code for testing also is to be instrumented before using the -c / --coverage option. I was unable to produce coverage information (just empty files) with the -c option. Tnx.

Edit: I've found your explanation for this in closed issues section. This can be deleted.

**Comment by dima117** [comment]
No, it doesn't. Please check that the test page uses your instrumented sourse code instead the initial code.
