### ISSUE TITLE
Hangs when grep results in no tests

### ISSUE THREAD

**Issue by Mr0grog** [direct-adv-interfaces/mocha-headless-chrome#3]
If the `grep` query argument causes no tests to be run, the test runner’s `end` event is fired synchronously and can’t be caught as [line 69 of `runner.js`](https://github.com/direct-adv-interfaces/mocha-headless-chrome/blob/master/runner.js#L69). The tests output “0 passing”, but then they just hang instead of closing.

For example, if I have the following in `browsertest.html`:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>In-Browser Mocha Tests</title>
        <link rel="stylesheet" href="../node_modules/mocha/mocha.css">
    </head>
    <body>
        <div id="mocha"></div>
        <script src="../node_modules/mocha/mocha.js"></script>
        <script>
            mocha.setup({ui: 'bdd'});

            describe('Test suite', function () {
                it('A single passing test', function() {
                    // this passes
                });
            });

            mocha.run();
        </script>
    </body>
</html>

```

Running this hangs:

```sh
mocha-headless-chrome --file test-plugins/browsertest.html?grep=unmatchable
```

If you pass a callback directly to `mocha.run()`, that seems to reliably get called in this scenario.

**Comment by Mr0grog** [comment]
The underlying cause is https://github.com/mochajs/mocha/issues/3065, but that may be considered working as intended.

**Comment by dima117** [comment]
Hi,

I will fix it today.

**Comment by dima117** [comment]
Done! `mocha-headless-chrome@1.5.2`

**Comment by Mr0grog** [comment]
Works great! Thanks so much for the quick response :)
