### ISSUE TITLE
Add option to run test suite in incognito mode

### ISSUE THREAD

**Issue by dima117** [direct-adv-interfaces/mocha-headless-chrome#31]
https://github.com/direct-adv-interfaces/mocha-headless-chrome/pull/28

In incognito mode, Chrome doesn't write any user data to disk. This can lead to significant speedups with test suites that use features like IndexedDB.

Note that when incognito is enabled, this will open two windows (one incognito and one non-incognito). I couldn't figured out how to suppress this behavior. It should be harmless though.

**Comment by dima117** [comment]
I was fixed the promlem and publish new package v2.0.1.

**Comment by lfairy** [comment]
Thanks! I am busy right now, but will test this when I get the time.
