### ISSUE TITLE
Failed tests do not throw errors

### ISSUE THREAD

**Issue by kettanaito** [direct-adv-interfaces/mocha-headless-chrome#4]
### What
When one of the tests fails, its report is visible in the console, however, it does not result into error.

### Why
This causes failed tests to have no effect on the build pipeline (CI), making build successful even on tests failure.

### Example
See [one of my builds](https://circleci.com/gh/kettanaito/sentinel-dom/8) with failed test.

### Expected behavior
Failed test should throw in the console to ensure proper CI.

**Comment by dima117** [comment]
Hi,

I will fix it today.

**Comment by kettanaito** [comment]
@dima117 Please let me know if you need any help with the fix. I am really looking forward to it :)

**Comment by dima117** [comment]
Done! `mocha-headless-chrome@1.5.1`
