### ISSUE TITLE
Console output handler adds a lot of blank lines

### ISSUE THREAD

**Issue by tildedave** [direct-adv-interfaces/mocha-headless-chrome#44]
Hi there.  In our test setup we periodically have a lot of newlines in the output.  This seems to be caused by the `stdout` checking behavior in this library, where if the log message doesn't come from mocha, a newline is inserted.  (This toggles between funny and annoying.)

![image](https://user-images.githubusercontent.com/405383/63186225-bfb79500-c010-11e9-8ab8-c1493d9c8c91.png)

We looked at removing all the console statements from our project and this didn't fix the issue, so our guess is that this is in one of the libraries that we're using.

Looking more into the details it looks like the console event from puppeteer is coming with no arguments, which causes the "not standard out" logic to be triggered, which adds a newline.  The empty list is blank so this ends up with a blank newline.

**Comment by dima117** [comment]
https://github.com/direct-adv-interfaces/mocha-headless-chrome/pull/45
