### ISSUE TITLE
Why would I want this?

### ISSUE THREAD

**Issue by akauppi** [direct-adv-interfaces/mocha-headless-chrome#5]
Got mocha and headless chrome to work just as such, so I'm wondering... what exactly is the use case for your repo?

The initial feeling I got from the `README` is that this would be needed to make mocha and puppeteer work. It's not. Please educate. Thanks.

**Comment by dima117** [comment]
Hi Asko,

`mocha-headless-chrome` will be useful if you want to use Mocha to write tests for code that uses browser API (for example tests for UI components).

Also you can use an alternative [mocha-puppeteer](https://www.npmjs.com/package/mocha-puppeteer) package that does the same, but has a different API (it has another CLI parameter set and it can't be used programmatically).

**Comment by dima117** [comment]
I think I can close this issue since it isn't active during several days. If you have any additional questions please open this issue again.
