### ISSUE TITLE
Error: m.setup is not a function at shimMochaInstance

### ISSUE THREAD

**Issue by iangilman** [direct-adv-interfaces/mocha-headless-chrome#6]
This library looks like just what I need! When I tried running it, I'm getting an error. Can you please point me in the right direction to sort it out?

```
$ node_modules/mocha-headless-chrome/bin/start -f http://localhost:8080
Error: TypeError: m.setup is not a function
    at shimMochaInstance (<anonymous>:10:11) 
    ...
```

Here's my test page, FWIW. It works fine in the browser.

```
<html>
<head>
  <meta charset="utf-8">
  <link href="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.css" rel="stylesheet" />
</head>
<body>
  <div id="mocha"></div>
  <script src="/static/build/lib.js"></script>
  <script src="/static/build/app.min.js"></script>
  <script src="http://chaijs.com/chai.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sinon@3/pkg/sinon.js"></script>
  <script src="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.js"></script>
  <script>mocha.setup('bdd')</script>
  <script src="/static/build/unit-tests.js"></script>
  <script>
    mocha.run();
  </script>
</body>
</html>
```

Thank you for any help you can provide!

**Comment by dima117** [comment]
Hi,

mocha-headless-chrome performs some additional mocha configuration at the moment when mocha instance set into the `mocha` global variable. In older versions of the Mocha, the value is [assigned](https://github.com/mochajs/mocha/blob/ebe9ceab96fc1a05d4c89b13c23824b94b01ec43/mocha.js#L6470) to the `mocha` global variable before it is [initialized](https://github.com/mochajs/mocha/blob/ebe9ceab96fc1a05d4c89b13c23824b94b01ec43/mocha.js#L6530). So mocha-headless-chrome is trying to configure uninitialized mocha instance and throws the error.

Please update your mocha to the version [2.3.0](https://cdnjs.com/libraries/mocha/2.3.0) or higher.

**Comment by iangilman** [comment]
Beautiful! That works perfectly... Thank you for the quick response!

I love how simple this package is to use, and the output is lovely :)

**Comment by iangilman** [comment]
Btw, I wonder if it might be possible to detect that it's the wrong Mocha and spit out an error telling the dev to upgrade? Just a thought.

**Comment by dima117** [comment]
It is no easy to recognize wrong library version since many variants of incorrect inclusion are possible. I added this info into the readme that user can check this yourself.

**Comment by iangilman** [comment]
Great... Adding the info to the readme is a help.

It seems maybe just a quick check for `m && m.setup` could catch a lot of cases, and you could spit out an error that said "make sure you have mocha 2.3.0 or later". Even if that didn't cover every possibility, it would still probably be a help.

Anyway, just giving ideas!
